### ISSUE TITLE
Update the cloud function to send PDF prescription via email.

### ISSUE THREAD

**Issue by VibhorKanojia** [covid19india/econsult-prescribe#16]

**Comment by VibhorKanojia** [comment]
Upon generating the PDF, the function should send the PDF to 
indiaeconsult.db@gmail.com,
patient's email ID (if provided)
doctor's email ID

**Comment by gaurav-kay** [comment]
Are we planning to use a delivery service like SendGrid or are we planning to send it from the function itself with nodemailer?

**Comment by pbteja1998** [comment]
@gaurav-kay are there any advantages of using Send Grid? Is it a free service?

**Comment by gaurav-kay** [comment]
From what I've looked up, SMTP servers have limitations on setting the from address and the number of mails sent per day, which even SendGrid has but we can provide custom "from" addresses.
SendGrid has a free tier
