### ISSUE TITLE
Integration with Tawk.to

### ISSUE THREAD

**Issue by VibhorKanojia** [covid19india/econsult-prescribe#7]
Currently the prescription module has a hardcoded prescription ID.
We would like this ID to be the same as the ticket ID that the doctor will generate on tawk.to.
For this, we would like to integrate this module with tawk.to.

Have a look at: https://developer.tawk.to/webhooks/
Inside there's a "Ticket created event" which will have the ticket ID available. The task is to use this webhook, get the ticket I, and send it to the prescription module.

**Comment by vicky002** [comment]
I'm looking into this one. Will update if my team takes this task.

**Comment by VibhorKanojia** [comment]
Going forward without the integration as this add unnecessary complexity to the current module.
